[package]
name = "ripasso"
version = "0.0.1"
authors = ["Joakim Lundborg <joakim.lundborg@gmail.com"]
licence = "GPL-3.0-or-later"
license-file = "LICENCE"

[dependencies]
notify = "4"
glob = "0.2"
gpgme = "0.8"
chrono = "0.4"
git2 = "0.7.5"
log = "0.4.5"
env_logger = "0.5"
dirs = "1.0"

[dev-dependencies]
tempdir = "0.3"

[workspace]

members = [
    "gtk","qml", "cursive"
]